import { AuthContextProvider } from "./context/AuthContext";
import type { Metadata } from 'next'
import { Roboto } from "next/font/google";
import Promo from './Promo';
import Navbar from './Navbar';
import Footer from './Footer';
import Header from './Header';
import './globals.css'

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: "Класна річ",
    description: "Мені попався класний товар",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthContextProvider>
          <Promo />
          <Navbar />
          <Header />
          <main className="max-w-7xl mx-auto w-full px-3 sm:px-6 py-5 flex-grow">
            {children}
          </main>
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  )
}
